-- Create table
create table DATA_DIODE_SCHEDULE_SETTING
(
  SETTING_ID NUMBER generated always as identity,
  NAME_JOB   VARCHAR2(100),
  TIME_CROSS VARCHAR2(100),
  IP_SERVER  VARCHAR2(255),
  JSON_PARAM CLOB,
  TYPE_JOB   NUMBER(1),
  TYPE_RUN   NUMBER(1),
  JOB_GROUP  VARCHAR2(255)
)

-- Create table
create table DATA_DIODE_SCHEDULE_PROCESSING
(
  PROCESSING_ID  NUMBER generated always as identity,
  SETTING_ID     NUMBER,
  TRANSACTION_ID VARCHAR2(100),
  SERVER_IP      VARCHAR2(255),
  IS_LAST        NUMBER(1),
  CREATE_DATE    TIMESTAMP(6) default current_timestamp
)

----------------  NOTI_STAY  ------------------------
create table DATA_DIODE_SYNC_NOTI_STAY (
    GUID varchar2(32) primary key not null,
    PAYLOAD clob,
    IS_LAST NUMBER(1) default 0,
    IS_MAX NUMBER(1) default 0,
    PROCESS_ID varchar2(32),
    PROCESS_DATE TIMESTAMP(6),
    PROCESS_STATUS number(1),
    PROCESS_MESS varchar2(500)
);

ALTER TABLE DATA_DIODE_SYNC_NOTI_STAY
ADD ID NUMBER AS (JSON_VALUE(PAYLOAD, '$.id' returning NUMBER));

ALTER TABLE DATA_DIODE_SYNC_NOTI_STAY
ADD UPDATED_DATE TIMESTAMP AS (NVL(TO_DATE(JSON_VALUE(PAYLOAD,'$.updatedDate'),'YYYY-MM-DD"T"HH24:MI:SS'),TO_DATE(JSON_VALUE(PAYLOAD,'$.createdDate'),'YYYY-MM-DD"T"HH24:MI:SS')));

create table DATA_DIODE_SYNC_NOTI_STAY_REF (
    GUID varchar2(32) primary key not null,
    PAYLOAD clob,
    IS_LAST NUMBER(1) default 0,
    IS_MAX NUMBER(1) default 0,
    PROCESS_ID varchar2(32),
    PROCESS_DATE TIMESTAMP(6),
    PROCESS_STATUS number(1),
    PROCESS_MESS varchar2(500)
);

ALTER TABLE DATA_DIODE_SYNC_NOTI_STAY_REF
ADD ID NUMBER AS (JSON_VALUE(PAYLOAD, '$.id' returning NUMBER));

ALTER TABLE DATA_DIODE_SYNC_NOTI_STAY_REF
ADD UPDATED_DATE TIMESTAMP AS (NVL(TO_DATE(JSON_VALUE(PAYLOAD,'$.updatedDate'),'YYYY-MM-DD"T"HH24:MI:SS'),TO_DATE(JSON_VALUE(PAYLOAD,'$.createdDate'),'YYYY-MM-DD"T"HH24:MI:SS')));

create table DATA_DIODE_SYNC_NOTI_STAY_MERGE (
    GUID varchar2(32) primary key not null,
    PAYLOAD clob,
    PAYLOAD_MERGE clob,
    PAYLOAD_MERGE_REF clob,
    PROCESS_ID varchar2(32),
    PROCESS_DATE TIMESTAMP(6),
    PROCESS_STATUS number(1),
    PROCESS_MESS varchar2(500),
    PROCESS_ID_REF varchar2(32),
    PROCESS_DATE_REF TIMESTAMP(6),
    PROCESS_STATUS_REF number(1),
    PROCESS_MESS_REF varchar2(500)
);

ALTER TABLE DATA_DIODE_SYNC_NOTI_STAY_MERGE
ADD ID NUMBER AS (JSON_VALUE(PAYLOAD, '$.id' returning NUMBER));

ALTER TABLE DATA_DIODE_SYNC_NOTI_STAY_MERGE
ADD ID_REF NUMBER AS (JSON_VALUE(PAYLOAD, '$.id_ref' returning NUMBER));
-----------------------------------------------------


create table DATA_DIODE_SYNC_ACCOM_FACILITY
as
select * from ACCOM_FACILITY where rownum <= 1;

create table DATA_DIODE_SYNC_ACCOM_FACILITY_REF
as
select * from ACCOM_FACILITY where rownum <= 1;

create table DATA_DIODE_SYNC_ACCOM_FACILITY_MERGE
as
select * from ACCOM_FACILITY where rownum <= 1;

create table DATA_DIODE_SYNC_REGIS_ACCOM_REPRESENTATIVE
as 
select * from REGIS_ACCOM_REPRESENTATIVE where rownum <= 1;

create table DATA_DIODE_SYNC_REGIS_ACCOM_REPRESENTATIVE_MERGE
as 
select * from REGIS_ACCOM_REPRESENTATIVE where rownum <= 1;

create table DATA_DIODE_SYNC_REGIS_ACCOM_REPRESENTATIVE_REF
as 
select * from REGIS_ACCOM_REPRESENTATIVE where rownum <= 1;

create table DATA_DIODE_SYNC_REGIS_GOVERNING_BODY
as
select * from REGIS_GOVERNING_BODY where rownum <= 1;

create table DATA_DIODE_SYNC_REGIS_GOVERNING_BODY_MERGE
as
select * from REGIS_GOVERNING_BODY where rownum <= 1;

create table DATA_DIODE_SYNC_REGIS_GOVERNING_BODY_REF
as
select * from REGIS_GOVERNING_BODY where rownum <= 1;

ALTER TABLE DATA_DIODE_SYNC_REGIS_GOVERNING_BODY_MERGE
ADD IS_LAST NUMBER(1) DEFAULT 1 NULL;
ALTER TABLE DATA_DIODE_SYNC_REGIS_GOVERNING_BODY_MERGE
ADD PROCESS_ID VARCHAR2(32 BYTE) NULL;
ALTER TABLE DATA_DIODE_SYNC_REGIS_GOVERNING_BODY_MERGE
ADD PROCESS_DATE TIMESTAMP(6) NULL;
ALTER TABLE DATA_DIODE_SYNC_REGIS_GOVERNING_BODY_MERGE
ADD PROCESS_STATUS NUMBER(1) NULL;
ALTER TABLE DATA_DIODE_SYNC_REGIS_GOVERNING_BODY_MERGE
ADD PROCESS_MESS VARCHAR2(500) NULL;

ALTER TABLE DATA_DIODE_SYNC_ACCOM_FACILITY_MERGE
ADD PROCESS_REF_ID VARCHAR2(32 BYTE) NULL;
ALTER TABLE DATA_DIODE_SYNC_ACCOM_FACILITY_MERGE
ADD PROCESS_REF_DATE TIMESTAMP(6) NULL;
ALTER TABLE DATA_DIODE_SYNC_ACCOM_FACILITY_MERGE
ADD PROCESS_REF_STATUS NUMBER(1) NULL;
ALTER TABLE DATA_DIODE_SYNC_ACCOM_FACILITY_MERGE
ADD PROCESS_REF_MESS VARCHAR2(500) NULL;

-- tao cot ao
ALTER TABLE DATA_DIODE_SYNC_ACCOM_FACILITY
ADD ID NUMBER AS (JSON_VALUE(PAYLOAD,'$.id'));

ALTER TABLE DATA_DIODE_SYNC_ACCOM_FACILITY
ADD GOVERNING_BODY_ID NUMBER AS(JSON_VALUE(PAYLOAD,'$.governingBodyId'));

ALTER TABLE DATA_DIODE_SYNC_ACCOM_FACILITY
ADD ACCOM_REPRESENTATIVE_ID NUMBER AS (JSON_VALUE(PAYLOAD,'$.accomRepresentativeId'));

ALTER TABLE DATA_DIODE_SYNC_ACCOM_FACILITY
ADD UPDATED_DATE TIMESTAMP AS (NVL(TO_DATE(JSON_VALUE(PAYLOAD,'$.updatedDate'),'YYYY-MM-DD"T"HH24:MI:SS'),TO_DATE(JSON_VALUE(PAYLOAD,'$.createdDate'),'YYYY-MM-DD"T"HH24:MI:SS')));